services:
  - type: web
    name: react-native-expo-web
    env: static
    buildCommand: yarn install && yarn build:web
    staticPublishPath: ./web-build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html